### ISSUE TITLE
read path attribute directly instead of doing send(...)

### ISSUE THREAD

**Issue by marshall-lee** [marshall-lee/acts_as_ltree#7]
I think it will be more correct to get a path value from object through `self[column_name]` but not with `send column_name`. It's "faster" and it's more correct in the context of a library. Methods, even if they're automatically created by ActiveRecord, belong to user's classes, not to us so we should neither invoke them nor make any assumption that they're exist. We work with `path` _attribute_, not with path _method_.

It must be changed everywhere in code.

**Comment by fluorescent-net** [comment]
All tests pass with changes in [this](https://github.com/marshall-lee/acts_as_ltree/commit/b249e36ce25c47095c7c0a6b28fc2406745aebdf) commit.
